M48
; DRILL file KiCad 10.0.5 date 2026-10-02T16:31:02
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-02T16:31:02-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X132.71Y-128.0
X134.213Y-88.0
X177.71Y-88.0
X177.71Y-128.75
M30
